services:
    frontend:
        build: ./Frontend
        ports:
            - 5173:5173
        volumes:
            - node_modules:/app/frontend/node_modules
        stdin_open: true
        tty: true

    backend:
        build: ./Backend
        ports:
            - 8080:8080
        depends_on:
            - db
            - redis

    db:
        image: 'postgres:17'
        environment:
            POSTGRES_PASSWORD: 12345
        volumes:
            - db-volume:/var/lib/postgresql/data/
            - ./dataset:/docker-entrypoint-initdb.d
    pgadmin:
        image: dpage/pgadmin4
        ports:
            - 80:80
        environment:
            PGADMIN_DEFAULT_EMAIL: user@domain.com
            PGADMIN_DEFAULT_PASSWORD: 12345
        depends_on:
            - db
        volumes:
            - pgadmin-volume:/var/lib/pgadmin/ 
    redis:
        image: redis:latest
volumes:
    pgadmin-volume:
    node_modules:
    db-volume: